feat(core): add LweToGlweSecretKeyTransmutationEngine
zama-ai/concrete-core pull request #14
Opened 2022-05-11 09:07 UTC by IceTDrinker

### Resolves:

closes #https://github.com/zama-ai/concrete-core-internal/issues/135

### Description

add LweToGlweSecretKeyTransmutationEngine
- add implementation for 32 and 64 bits keys
- add fixtures
- add case to test and bench apps

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
* [ ] The draft release description has been updated
* [x] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-05-11 13:40 UTC, aPere3 requested changes
Hello @IceTDrinker ,

Thanks for this PR ! 

I just have one comment on the fixture, where you could remove the parameters from the context, but otherwise it looks good ! 

Best,

Alex

2022-05-11 13:40 UTC, aPere3 commented on concrete-core-fixture/src/fixture/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    type PostExecutionContext = (OutputSecretKey, LweDimension, PolynomialSize);
Here, you don't need to put the `PolynomialSize` and the `LweDimension` in the pre/post execution context, because those are already passed to the functions in the `parameters` argument :wink:

2022-05-11 13:45 UTC, IceTDrinker commented on concrete-core-fixture/src/fixture/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +        expected == actual
ok yes I see, in my mind the fixtures in a way are "thorough correctness tests", doc tests being "just" an example of how to use the API (that should still be correct of course).

I know this PR needs to be rebased on the split anyways so if you think I should follow a different path for the fixture I'll happily do so 🙂

2022-05-12 14:07 UTC, IceTDrinker commented
has to be merged after https://github.com/zama-ai/concrete-core/pull/15

2022-05-12 15:21 UTC, agnesLeroy approved these changes
Hi @IceTDrinker! It looks great, thanks a lot! There are just some missing destroys in the doc test, maybe they are missing in the other transmute engine too (in that case could you also add them please?). :pray:

2022-05-12 15:21 UTC, agnesLeroy commented on concrete-core/src/backends/default/implementation/engines/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    ///
Here you have to add the destroy calls

2022-05-12 15:21 UTC, agnesLeroy commented on concrete-core/src/backends/default/implementation/engines/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    ///
Same here

2022-05-12 15:22 UTC, IceTDrinker commented on concrete-core/src/backends/default/implementation/engines/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    ///
ah thanks! I'll check for the other as well 🙂

2022-05-12 15:27 UTC, IceTDrinker commented on concrete-core/src/backends/default/implementation/engines/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    ///
yep looks like they were missing there too!

2022-05-12 15:31 UTC, IceTDrinker commented on concrete-core/src/backends/default/implementation/engines/lwe_secret_key_to_glwe_secret_key_transmutation.rs
> +    ///
done !

2022-05-12 15:51 UTC, IceTDrinker commented
fixed a filename

2022-05-12 15:55 UTC, agnesLeroy commented on concrete-core/src/backends/default/implementation/engines/lwe_to_glwe_secret_key_transmutation.rs
> +    /// engine.destroy(glwe_secret_key)?;
Oh you also need to destroy the lwe secret key: basically all the entities that were created via an engine.

2022-05-13 07:26 UTC, merged