Feat/bit extract
zama-ai/concrete-core pull request #154
Opened 2022-09-01 14:16 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-09-01 14:16 UTC, agnesLeroy commented
@slab-ci cpu_test

2022-09-02 11:02 UTC, IceTDrinker reviewed
Only did the first commit for now

2022-09-02 11:02 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs
> +    /// let output_lwe_sk: LweSecretKey32 = default_engine.generate_new_lwe_secret_key(lwe_dim)?;
the big lwe sk needs to be the glwe key transformed into an lwe key I think when looking at the extract bit test from the private implementation tests, otherwise there will be an issue for the bit subtraction from the original lwe_in, maybe we are missing a check in the public API (that you added in the private one but in debug assert)

2022-09-02 11:11 UTC, agnesLeroy commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/mod.rs
> +            }
It's only in the backend implementation that we have the information about the actual type of the entity, so I can't do this check at the specification level.

2022-09-02 11:17 UTC, agnesLeroy commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs
> +    /// let output_lwe_sk: LweSecretKey32 = default_engine.generate_new_lwe_secret_key(lwe_dim)?;
I need to change the fixture as well then: surprising that the test is passing

2022-09-02 11:20 UTC, agnesLeroy commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +/// most significant bits, starting from the bit at index `delta_log` (0-indexed) included.
I changed the comment

2022-09-02 11:22 UTC, agnesLeroy commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs
> +    /// let output_lwe_sk: LweSecretKey32 = default_engine.generate_new_lwe_secret_key(lwe_dim)?;
But in the checks we can only verify that the dimensions are correct, not that the keys themselves were created properly, so I won't be able to check that the input LWE key is actually a transformation of the GLWE key used to build the bootstrap key :thinking:

2022-09-02 11:50 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs
> +    /// let output_lwe_sk: LweSecretKey32 = default_engine.generate_new_lwe_secret_key(lwe_dim)?;
yep I understand that, haven't had time to read the fixture yet

2022-09-02 11:51 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/mod.rs
> +            }
what I often see is we pass the relevant sizes and perform the check anyways 🤔

2022-09-02 12:16 UTC, IceTDrinker requested changes
Regarding the weird results we seem to be seeing

I think we are only extracting 0s from the parameters and the way the plaintext is shifted, I don't get why the noise distribution looks ok when we don't seem to be using the same keys for the output of the bootstrap (glwe) and the input ct (lwe)

Maybe we can update the fixture to check for the actual bits that are extracted as well

Putting a request change here as merging this feels dangerous

2022-09-02 12:16 UTC, IceTDrinker commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +                },
were those parameters validated/checked by our fellow cryptographers ?

2022-09-02 12:16 UTC, IceTDrinker commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +        let proto_plaintext = maker.transform_raw_to_plaintext(&raw_plaintext);
the raw_plaintext does not look to be shifted to delta_log

we probably want a random plaintext each time ?

2022-09-02 12:16 UTC, IceTDrinker commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +        )
in addition to returning the these values, we can maybe also return the decrypted bits to check we recover the values we expect ?

2022-09-02 13:32 UTC, agnesLeroy commented
@slab-ci cpu_test

2022-09-02 13:44 UTC, IceTDrinker commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +        let raw_plaintext = Precision::Raw::ONE << (Precision::Raw::BITS - 5);
this means we only have a single bit set, we should rather generate a message in the range [0; 2 ^ Number of bits to extract - 1] and then shift it ?

2022-09-05 08:18 UTC, agnesLeroy commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/mod.rs
> +            }
Oh right, I can definitely do that :sweat_smile:

2022-09-05 08:18 UTC, agnesLeroy commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +        if input.lwe_dimension().0 != bsk.polynomial_size().0 * bsk.glwe_dimension().0 {
Changed locally

2022-09-05 17:00 UTC, agnesLeroy commented on concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs
> +    /// let output_lwe_sk: LweSecretKey32 = default_engine.generate_new_lwe_secret_key(lwe_dim)?;
I just updated the doc test. We'll deal with the fixture in another PR.

2022-09-05 17:01 UTC, agnesLeroy commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +                },
No, I'll create another PR for the fixture alone.

2022-09-05 17:01 UTC, agnesLeroy commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +        let proto_plaintext = maker.transform_raw_to_plaintext(&raw_plaintext);
Will keep this in mind for the fixture PR

2022-09-05 17:02 UTC, agnesLeroy commented on concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bit_extraction.rs
> +        )
Again let's deal with this in the fixture PR

2022-09-05 17:04 UTC, agnesLeroy commented
@slab-ci cpu_test

2022-09-06 06:55 UTC, agnesLeroy commented
@slab-ci cpu_test

2022-09-06 07:50 UTC, IceTDrinker commented
could you rebase it on main before I review ? so that we don't get the extra commits in the diff view 🙂

2022-09-06 08:17 UTC, agnesLeroy commented
> could you rebase it on main before I review ? so that we don't get the extra commits in the diff view slightly_smiling_face

Done!

2022-09-06 08:36 UTC, IceTDrinker commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +                                  the output one of the keyswitch key.",
The output ciphertext vector **LWE** dimension must be the same **as** the output **LWE dimension** of the keyswitch key.

2022-09-06 08:36 UTC, IceTDrinker commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +    ExtractedBitsCountMismatch => "The output LWE ciphertext vector count must be the same than \
same as

2022-09-06 08:36 UTC, IceTDrinker commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +    KeyDimensionMismatch => "The keyswitch key output LWE dimension must be the same than the \
same as

2022-09-06 08:36 UTC, IceTDrinker commented on concrete-core/src/specification/engines/lwe_ciphertext_discarding_bit_extraction.rs
> +                              not exceed the total number of available bits in the ciphertext"
from bit at index delta_log (?)

2022-09-06 08:49 UTC, IceTDrinker approved these changes
Looks ok to my tired eyes 👍

2022-09-06 10:22 UTC, merged