chore(ci): small fixes to aws_test.yml
zama-ai/concrete-core pull request #22
Opened 2022-05-19 15:37 UTC by IceTDrinker

### Resolves:

closes https://github.com/zama-ai/concrete-core-internal/issues/156

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-05-20 09:10 UTC, soonum requested changes

2022-05-20 10:17 UTC, IceTDrinker commented on .github/workflows/docs_core.yml
> +        run: echo "RELEASE_VERSION=${GITHUB_REF#$TAG_REFS_FILTER}" >> "$GITHUB_ENV"
In bash curly braces are used disambiguate the name of variable https://stackoverflow.com/a/8748880/18088947

Here it's not a big problem as the name of the variable is GITHUB_ENV, though I personally started using curly braces everywhere, I'll add the braces here

2022-05-20 10:30 UTC, IceTDrinker commented on .github/workflows/aws_tests.yml
> +        echo "HOME=/home/ubuntu" >> "${GITHUB_ENV}"
I'll make a short and long answer 🙂 

The tools I used to lint the workflows are actionlint: https://github.com/rhysd/actionlint and shellcheck which lints the shell scripts: https://github.com/koalaman/shellcheck (forgot to link the issue : https://github.com/zama-ai/concrete-core-internal/issues/154), it's now a default check on PRs in CML. The two tools combined pointed out the lack of double quotes on the GITHUB_ENV variable.

First if nothing is specified a `run: |` command in GitHub workflow uses the default shell which should be `bash` on ubuntu-based runners which we use. (This can be modified per step or per job by changing the shell or setting the default shell for a job, more info here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-set-the-default-shell-and-working-directory)

Short answer:

You nearly always want to put quotes when you use a bash variable either "$VARIABLE" or "${VARIABLE}" because otherwise if there is a space in the string it is going to be interpreted as separate commands. In some rare cases you want the split to happen at spaces, but it's the exception more than the rule from what I could see. It's a common vulnerability for shell script. E.g.:

```bash
echo $ENV_VAR
```

If someone has set ENV_VAR="'pwned!'; rm -rf *" then the script above will output "pwned!" and remove all the files and directories in the working directory you have the right to delete, imagine if the script is run as sudo and you just launch a different script altogether with a nasty payload!

So double quotes everywhere should be the default as it prevents the expansion of harmful commands/unwanted behaviors when using bash variables.

Long answer:

In github actions it hardly matters as the GITHUB_ENV variable is a non pathologic path to a temporary file to store env variables for future steps. Basically a collection of statements like:

```
VAR_1=value1
VAR_2=value2
```

which are sourced for later steps making them available for other steps, this is useful if you have scripts automatically populating some parameters for future steps.

So using `echo "MY_VAR=value" >> $GITHUB_ENV` will translate to:

`echo "MY_VAR=value" >> /tmp/some_path/to/a_special_env_file/` and append `MY_VAR=value` to the env file for future steps.

However I prefer to listen to linters and use best practices wherever possible hence why I double quote nearly everywhere and added those here 🙂 

Also if for whatever reason someone manages to compromise the GITHUB_ENV variable then you protect yourself from weird commands and will just have a weird crash in CI. Though if that variable is compromised you most likely already lost the war to your attacker!

2022-05-20 10:37 UTC, soonum commented on .github/workflows/docs_core.yml
> +        run: echo "RELEASE_VERSION=${GITHUB_REF#$TAG_REFS_FILTER}" >> "$GITHUB_ENV"
That's perfect, thanks for the SO link.

2022-05-20 10:41 UTC, soonum commented on .github/workflows/aws_tests.yml
> +        echo "HOME=/home/ubuntu" >> "${GITHUB_ENV}"
The insights that you provided are very useful thanks a lot.
I agree with you on linters usage and good practices. I didn't about those tools and I will definitely use them myself.

2022-05-20 10:44 UTC, soonum approved these changes

2022-05-20 11:35 UTC, IceTDrinker commented on .github/workflows/aws_tests.yml
> +        echo "HOME=/home/ubuntu" >> "${GITHUB_ENV}"
A correction on the ENV variable thing, it seems an env variable is not split on spaces, here is a proper explanation on the potential vulnerability: https://unix.stackexchange.com/a/171347

The spirit is the same but my example was wrong, sorry about that!

2022-05-23 07:12 UTC, agnesLeroy approved these changes
Thanks a lot for this @IceTDrinker! :heart:

2022-05-23 07:13 UTC, merged