feat(core): add backward GGSW Fourier conversion to FFT backend
zama-ai/concrete-core pull request #261
Opened 2022-11-03 14:39 UTC by agnesLeroy

### Resolves: https://github.com/zama-ai/concrete-core-internal/issues/468

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-03 16:02 UTC, sarah-ek requested changes

2022-11-03 16:02 UTC, sarah-ek commented on concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
> +            .fill_with_backward_fourier(output.0.clone(), fft, self.stack());
here we're modifying a clone of the output, and not the output itself. `fill_with_backward_fourier` should be changed to take a mutable slice type, and this should pass to it `output.0.as_mut_view()`

2022-11-03 16:02 UTC, sarah-ek commented on concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
> +            .fill_with_backward_fourier(output.0.clone(), fft, self.stack());
same comment here. we're modifying a clone of the output, and not the output itself

2022-11-03 16:02 UTC, sarah-ek commented on concrete-core/src/backends/fft/private/crypto/ggsw.rs
> +        mut coef_ggsw: StandardGgswCiphertext<Vec<Scalar>>,
`coef_ggsw`'s type should be `StandardGgswCiphertext<&mut [Scalar]>`. that way we can modify the output through the view that we receive.

2022-11-03 16:46 UTC, agnesLeroy commented on concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
> +            .fill_with_backward_fourier(output.0.clone(), fft, self.stack());
Oh sure, just fixed it! Thank you :slightly_smiling_face:

2022-11-03 16:46 UTC, agnesLeroy commented on concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
> +            .fill_with_backward_fourier(output.0.clone(), fft, self.stack());
Fixed

2022-11-03 16:46 UTC, agnesLeroy commented on concrete-core/src/backends/fft/private/crypto/ggsw.rs
> +        mut coef_ggsw: StandardGgswCiphertext<Vec<Scalar>>,
Fixed

2022-11-04 09:49 UTC, sarah-ek approved these changes

2022-11-04 09:54 UTC, merged