chore(cuda): replace casts with cuda intrinsics
zama-ai/concrete-core pull request #263
Opened 2022-11-04 10:46 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-04 10:46 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-04 14:24 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-10 12:39 UTC, agnesLeroy commented
@bbarbakadze this change doesn't seem to modify benchmark results significantly, but still I think we can merge, wdyt?

2022-11-10 12:49 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-10 13:48 UTC, pdroalves commented
I like the idea of simplifying things by using intrinsics.

2022-11-14 12:30 UTC, bbarbakadze approved these changes

2022-11-14 12:33 UTC, pdroalves requested changes
Adding my reviews.

2022-11-14 13:02 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> -    dst[tid].y = y / (double)std::numeric_limits<T>::max();
wow that's a mistake: I thought this function was not being used and the tests pass. I'll make sure the CI launches all the tests so we catch this kind of things easily.

2022-11-14 13:03 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> -    dst[tid].y = y / (double)std::numeric_limits<T>::max();
I'll also check whether we normalize the bsk/ggsw elements when casting them to signed values, and whether we normalize decomposed elements as well in the CPU implementation.

2022-11-14 14:14 UTC, pdroalves commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> -    dst[tid].y = y / (double)std::numeric_limits<T>::max();
Weird =/

```
➜  concrete-core-pr git:(cuda/chore/casts) ✗ cargo test -p concrete-core --release --features=backend_cuda,backend_fft,backend_default_parallel -- --test cuda_cmux_tree
   Compiling concrete-cuda v0.1.1 (/home/zama/ZamaCode/concrete-core-pr/concrete-cuda)
   Compiling concrete-core v1.0.1 (/home/zama/ZamaCode/concrete-core-pr/concrete-core)
    Finished release [optimized] target(s) in 1m 12s
     Running unittests src/lib.rs (target/release/deps/concrete_core-8e8df38d323373ca)

running 1 test
test backends::cuda::private::wopbs::test::test_cuda_cmux_tree ... FAILED

failures:

---- backends::cuda::private::wopbs::test::test_cuda_cmux_tree stdout ----
polynomial_size: 512, glwe_dimension: 1, level: 3, base_log: 6
r: 10
glwe_size: 1024, ggsw_size: 6144

We have 1024 LUTs
vec_msg: 1
vec_msg: 0
vec_msg: 1
vec_msg: 1
vec_msg: 1
vec_msg: 1
vec_msg: 0
vec_msg: 0
vec_msg: 0
vec_msg: 0
We have 10 ggsw

result: 10716807896010784770
witness : 13
lut_number: 9
Done!
thread 'backends::cuda::private::wopbs::test::test_cuda_cmux_tree' panicked at 'assertion failed: `(left == right)`
  left: `9`,
 right: `13`', concrete-core/src/backends/cuda/private/wopbs/test.rs:176:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    backends::cuda::private::wopbs::test::test_cuda_cmux_tree

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 76 filtered out; finished in 0.21s

error: test failed, to rerun pass '-p concrete-core --lib'
```

2022-11-14 17:31 UTC, pdroalves commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> -    dst[tid].y = y / (double)std::numeric_limits<T>::max();
After investigating, I concluded that the problem is in the new typecast_double_to_torus. Possibly that intrinsic may miss the msb after casting. A different implementation of it might be expected on different architectures. That explains why it doesn't work on my machine but works on @agnesLeroy 's and on the V100 VM.

My suggestion is to rollback the 64-bit version:

```
template <>
__device__ inline void typecast_double_to_torus<uint64_t>(double x, uint64_t& r) {
    uint128 nnnn = make_uint128_from_float(x);
    uint64_t lll = nnnn.lo_;
    r = lll;
}
```

2022-11-15 07:55 UTC, agnesLeroy commented on concrete-cuda/cuda/src/crypto/torus.cuh
> +  output = round((double)element / (double(std::numeric_limits<T>::max()) + 1.0) *
Actually I would have kept the T::max division, it looks like what's done in the CPU implementation and in the GGSW conversion (if that's ok for you).

2022-11-15 08:43 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> -    dst[tid].y = y / (double)std::numeric_limits<T>::max();
I've reverted the change then: could you let me know if it now works on your laptop?

2022-11-16 13:18 UTC, pdroalves approved these changes
I've ran that test 100 times and it passed in all of them. I think we are good to go.

2022-11-16 13:22 UTC, merged