feat(cuda): Refactor all host functions in concrete-cuda to use asynchronous allocation
zama-ai/concrete-core pull request #266
Opened 2022-11-07 15:56 UTC by pdroalves

### Resolves: https://github.com/zama-ai/concrete-core-internal/issues/430

### Description
Two functions are implemented to encapsulate the asynchronous allocation and freeing of device memory. If the installed toolkit version is less than 11.2, use synchronous.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-07 15:56 UTC, pdroalves commented
@slab-ci cpu_test

2022-11-07 16:16 UTC, agnesLeroy reviewed
Just an initial comment: don't we need to check for the Cuda version like you did for the wop PBS with:
```
#if (CUDART_VERSION < 11020)
...
```
?

2022-11-07 16:40 UTC, agnesLeroy commented
Oh great! Sorry I had missed it!

2022-11-08 08:03 UTC, agnesLeroy requested changes
Hi @pdroalves! Thanks a lot for this PR, it looks good :slightly_smiling_face: I just have two minor comments, otherwise it'll be good to me :+1:

2022-11-08 08:03 UTC, agnesLeroy commented on concrete-cuda/cuda/src/device.cu
> +void *cuda_malloc_async(uint64_t size, void *v_stream) {
Here I would pass a cuda stream rather than a void pointer, and avoid having to cast the void pointer to a cuda stream every time the functions are called.

2022-11-08 13:18 UTC, pdroalves commented on concrete-cuda/cuda/src/device.cu
> +void *cuda_malloc_async(uint64_t size, void *v_stream) {
Agreed. I was trying to keep consistency with other methods in that file, as cuda_memcpy_async_to_gpu. Do you think in the future we should refactor those too?

2022-11-08 13:18 UTC, pdroalves commented
@slab-ci gpu_test

2022-11-08 13:18 UTC, pdroalves commented
@slab-ci cpu_test

2022-11-09 08:41 UTC, agnesLeroy commented on concrete-cuda/cuda/src/device.cu
> +void *cuda_malloc_async(uint64_t size, void *v_stream) {
Yes probably :slightly_smiling_face:

2022-11-09 08:41 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bootstrap_wop.cuh
> +    d_mem = (char*) cuda_malloc_async(memory_needed_per_block * (1 << (r - 1)), v_stream);
Oh ok, forget it then :sweat_smile:

2022-11-09 08:42 UTC, agnesLeroy approved these changes

2022-11-09 08:44 UTC, merged