feat(cuda): add lwe / cleartext multiplication GPU acceleration
zama-ai/concrete-core pull request #267
Opened 2022-11-08 10:28 UTC by agnesLeroy

### Resolves: https://github.com/zama-ai/concrete-core-internal/issues/461

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-08 10:45 UTC, agnesLeroy commented
@slab-ci cpu_test

2022-11-08 10:45 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-08 10:53 UTC, agnesLeroy commented
@pdroalves I'll fix formatting after the tests have run sorry for this. :slightly_smiling_face:

2022-11-08 21:10 UTC, pdroalves requested changes

2022-11-08 21:10 UTC, pdroalves commented on concrete-core/src/backends/cuda/private/crypto/cleartext/list.rs
> +            compute_number_of_samples_on_gpu(number_of_gpus, count, GpuIndex(gpu_index)).0;
This part is a little confusing for me. Each iteration should process `chunk`, which has size `samples_on_gpu_0`. However, it also computes `alloc_size`, which is the number of samples that can be processed by some (maybe not-zero) GPU, allocates `alloc_size * sizeof(T)` bytes, and copy `chunk.len()` or `chunk.len() + samples_on_gpu_0` bytes. This can led to an undesired behavior.

I suggest this piece of code to be refactored so that each iteration receives `chunk` from a vector/slice and does all following computation considering only the size of that `chunk`.

2022-11-08 21:15 UTC, pdroalves commented
Hey @agnesLeroy !
The tests are passing and most of things look good to me. There is a single point that came to my eyes, which is the size used to allocate device memory not being 100% related to the vector being copied. I'm afraid that is also being done [for plaintexts](https://github.com/zama-ai/concrete-core/blob/main/concrete-core/src/backends/cuda/private/crypto/plaintext/list.rs).

Do you agree that's really a problem?

2022-11-09 08:19 UTC, agnesLeroy commented
> Hey @agnesLeroy ! The tests are passing and most of things look good to me. There is a single point that came to my eyes, which is the size used to allocate device memory not being 100% related to the vector being copied. I'm afraid that is also being done [for plaintexts](https://github.com/zama-ai/concrete-core/blob/main/concrete-core/src/backends/cuda/private/crypto/plaintext/list.rs).
> 
> Do you agree that's really a problem?

Why do you says it's not 100% related?

2022-11-09 14:04 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-09 14:07 UTC, pdroalves approved these changes
Thanks for the modifications @agnesLeroy ! 
I think we have something much better now :-D

2022-11-09 14:31 UTC, merged