chore(fixture): modify params for pbs test and number of repetitions
zama-ai/concrete-core pull request #282
Opened 2022-11-21 15:59 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-21 15:59 UTC, agnesLeroy commented
@slab-ci cpu_test
@slab-ci gpu_test

2022-11-22 13:19 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-22 14:18 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-22 16:05 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-23 13:01 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-23 16:24 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-24 10:23 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 08:48 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 10:20 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 14:07 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 14:15 UTC, bbarbakadze requested changes

2022-11-28 14:18 UTC, agnesLeroy commented on concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
> +  cuda_drop_async(d_bsk, *stream, gpu_index);
Yes definitely!

2022-11-28 14:19 UTC, agnesLeroy commented on concrete-cuda/cuda/src/fft/bnsmfft.cuh
> +  double2 *fft = buffer;
Indeed, this is replaced by
double2 *fft = &buffer[blockIdx.x * polynomial_size];

2022-11-28 14:29 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 14:36 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-28 14:37 UTC, agnesLeroy commented on concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
> +          (double2 *)cuda_malloc_async(shared_memory_size, *stream, gpu_index);
definitely!

2022-11-28 15:32 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-11-29 08:00 UTC, merged