chore(ci): enable concrete-cuda benchmarks on slab
zama-ai/concrete-core pull request #285
Opened 2022-11-23 18:13 UTC by soonum

### Description

Concrete-cuda benchmarks can be run either from a Pull Request or can be started using start_gpu_benchmark.yml.
On each push on main branch this workflow will be triggered. Results are parsed and sent to Slab CI server which will in turn make them available in our Grafana instance.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-11-23 20:33 UTC, agnesLeroy requested changes

2022-11-23 20:33 UTC, agnesLeroy commented on ci/slab.toml
> +instance_type = "p3.16xlarge"
I think p3.2xlarge would be enough considering that we don't do multi GPU :slightly_smiling_face: -> p3.2xlarge instead

2022-11-24 08:24 UTC, soonum commented on ci/slab.toml
> +instance_type = "p3.16xlarge"
I hope we won't have to much variation between runs then.

2022-11-24 08:52 UTC, agnesLeroy approved these changes

2022-11-24 08:52 UTC, agnesLeroy approved these changes

2022-11-24 08:53 UTC, merged