Feat/cuda wop
zama-ai/concrete-core pull request #311
Opened 2022-12-16 14:11 UTC by agnesLeroy

### Resolves: https://github.com/zama-ai/concrete-core-internal/issues/492

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-12-16 14:11 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-12-16 14:12 UTC, agnesLeroy commented
@slab-ci gpu_test

2022-12-16 16:32 UTC, pdroalves requested changes

2022-12-16 16:32 UTC, pdroalves commented on concrete-cuda/cuda/src/bit_extraction.cu
> +          "number of streaming multiprocessors on the device divided by 8 * "
This phrase doesn't match with the equation.

2022-12-16 16:35 UTC, pdroalves commented on concrete-cuda/cuda/src/bit_extraction.cu
> +          "number of streaming multiprocessors on the device divided by 8 * "
I believe the mistake is in the equation, that should be 

```
number_of_samples <= number_of_sm * 4. / 2. / level_count_bsk
```

as in https://github.com/zama-ai/concrete-core/blob/c3a2b083c2e8fc2226e2730424783cf5595dce9a/concrete-cuda/cuda/src/wop_bootstrap.cu (line 28).

Do you agree @bbarbakadze ?

2022-12-20 13:34 UTC, pdroalves commented
@slab-ci cpu_test
@slab-ci gpu_test

2022-12-20 13:36 UTC, pdroalves commented on concrete-cuda/cuda/src/bit_extraction.cu
> +          "number of streaming multiprocessors on the device divided by 8 * "
@agnesLeroy I've modified the formula to match the description. Let's double check it together when you are back.

2022-12-20 13:37 UTC, pdroalves approved these changes

2022-12-20 15:49 UTC, merged