chore(cuda): create scratch function and cleanup for wop pbs
zama-ai/concrete-core pull request #321
Opened 2023-01-24 11:12 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-01-24 11:12 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-25 17:13 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-26 08:28 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-26 09:27 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-27 13:22 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-27 17:18 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-27 17:58 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-01-27 19:03 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-06 09:04 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-06 15:31 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-06 16:28 UTC, agnesLeroy commented
Hi @pdroalves @bbarbakadze! This is a first iteration to create scratch functions for the wop PBS & PBS. Here I only work on the wop PBS, and I do not handle all the "layers" of buffers. I just wanted to have your opinion on this part first, so that we can see if this is the right direction.

I have hesitated to pass a single buffer pointer to the wop PBS (maybe 2, since we have void typed buffers and a u32 one), then use different chunks of the big void buffer to create all the intermediary buffers we need. I could do that in this PR, it would avoid passing many arguments to the wopPBS and cbs+vp functions.

What do you think?

2023-02-07 07:52 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-08 13:34 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-08 13:37 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-08 13:42 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-08 13:45 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-08 15:14 UTC, pdroalves requested changes
Thanks for this PR @agnesLeroy !
I like the direction we are going with this.

I would have started this process by the lower-level blocks, as the classical PBSs for instance. I guess ideally `scratch_cuda_circuit_bootstrap_vertical_packing_*` and `scratch_cuda_wop_pbs_*` should call and add to their buffer the results of `get_buffer_size_* ` for each of those blocks, as some sort of "Composition" design pattern. Is this what you have in mind?

2023-02-08 15:14 UTC, pdroalves commented on concrete-core/src/backends/cuda/private/device.rs
> +            cuda_synchronize_stream(self.stream.0);
Same here.

2023-02-08 15:14 UTC, pdroalves commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
>        (uint32_t *)malloc(number_of_inputs * level_count_cbs * sizeof(uint32_t));
This `malloc`, between a `cudaMalloc` and a `cudaMemcpy`, is probably blocking the stream. We should move this line before the first `cudaMalloc` so that we allocate / initialize `h_lut_vector_indexes` and only then we do the GPU operations.

2023-02-08 15:14 UTC, pdroalves commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
> +         + (2 * polynomial_size) * sizeof(Torus) // lut_pbs
Can you replace this by `(glwe_dimension+1) * polynomial_size`? The future Pedro says thank you :-P

2023-02-08 16:03 UTC, agnesLeroy commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
> +  free(h_lut_vector_indexes);
Totally

2023-02-08 16:07 UTC, agnesLeroy commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
> +         + (2 * polynomial_size) * sizeof(Torus) // lut_pbs
Yes, totally. Should I replace the other `polynomial_size` with `glwe_dimension * polynomial_size` by the way?

2023-02-08 16:09 UTC, agnesLeroy commented on concrete-core/src/backends/cuda/private/crypto/wopbs/test.rs
> +            cuda_synchronize_stream(
Yes, I'll remove them.

2023-02-08 17:29 UTC, pdroalves commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
> +         + (2 * polynomial_size) * sizeof(Torus) // lut_pbs
Sorry I couldn't find it. Which other?

2023-02-09 08:41 UTC, agnesLeroy commented on concrete-cuda/cuda/src/wop_bootstrap.cuh
> +         + (2 * polynomial_size) * sizeof(Torus) // lut_pbs
There are several buffers that involve a (polynomial_size + 1) term (lwe_array_in_buffer, lwe_array_in_shifted_buffer, lwe_array_out_pbs_buffer). I'm wondering if I should put glwe_dimension * (polynomial_size + 1) instead.

2023-02-09 12:41 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-09 12:43 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-09 13:07 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-09 16:26 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-13 17:22 UTC, pdroalves approved these changes
I think we are good to go!

2023-02-14 08:21 UTC, merged