refactor(cuda): Refactor the amortized PBS to support k > 1
zama-ai/concrete-core pull request #323
Opened 2023-02-07 22:01 UTC by pdroalves

### Resolves: https://github.com/zama-ai/concrete-core-internal/issues/448

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-02-07 23:02 UTC, pdroalves commented
To add support for k>1 in the amortized PBS I had to refactor and fix things all over the crate, including some common methods to the low latency kernel.

2023-02-07 23:03 UTC, pdroalves commented
@slab-ci gpu_test

2023-02-08 09:48 UTC, agnesLeroy requested changes
Hi @pdroalves! Thanks a lot for this PR, the code looks much more readable to me now! I have a few remarks you'll see, nothing major :slightly_smiling_face: You did an amazing job!

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +  cudaDeviceSynchronize();
I think we should remove this synchronize from here: in the PR where I fixed the asynchronous behaviour I removed them all, and called them from the tests or the Rust integration instead.

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/crypto/gadget.cuh
> +    for (int j = 0; j < num_poly; j++) {
Here I can see how the bootstrap code is simpler by doing the decomposition on every mask/body element in the same function, but we should probably change the function name to something like `decompose_and_compress_next_glwe` (name to be discussed) to make it clearer in the name that it's not only one value that's being dealt with. Also, this deserves an explanation in a comment for the function.

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +  for (int z = 0; z < (glwe_dimension + 1); z++) {
I have the same remark here: the function name should be adapted to reflect this change, and a comment should be added to make it clear that it handles all GLWE dimensions, not just one value.

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +  for (int z = 0; z < (glwe_dimension + 1); z++) {
Same here.

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +  for (int z = 0; z < (glwe_dimension + 1); z++) {
Same here again.

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +    // accumulator.reverse_inplace();
We could remove those commented lines maybe?

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +    // accumulator.multiply_by_monomial_negacyclic_inplace(1);
Maybe we could remove these commented lines as well?

2023-02-08 09:48 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +    // accumulator.copy_into(lwe_array_out);
Here again line 266 could be removed.

2023-02-08 17:14 UTC, pdroalves commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +  cudaDeviceSynchronize();
Ops, this is a debug artifact. I forgot to remove :sweat_smile:.

2023-02-08 17:23 UTC, pdroalves commented on concrete-cuda/cuda/src/crypto/gadget.cuh
> +    for (int j = 0; j < num_poly; j++) {
Something that is not clear to me is how generic this function is (as well as all functions in `functions.cuh`). As I see, this gadget class can be used to decompose any number of polynomials concatenated in an array. These can be a GLWE with any dimension, but also anything else. For instance, I have yet to start the refactoring of the low latency kernel, but I believe one path we could take there is to have different y-blocks handling each polynomial in the mask. In that case, we would need each `decompose_and_compress_next` to decompose a single polynomial and not the entire GLWE. So I'm not very supportive in using "glwe" there unless we have sure we will never use these functions to anything than on GLWEs. What do you think?

Otherwise, I think just adding a comment explaining the class would be enough.

2023-02-08 17:25 UTC, pdroalves commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +    // accumulator.reverse_inplace();
These comments were quite useful to me to understand what is being done in each part of the function. I would keep them.

2023-02-08 20:17 UTC, pdroalves commented
Should we simply ignore the CPU test? I think this is one of those problematic statistical tests.

2023-02-09 08:11 UTC, agnesLeroy commented on concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_3.rs
> +                    - <Precision::Raw as CastInto<i64>>::cast_into(obtained))
Is this not the same check as in the fixture 2? Why did you add the fixture 3?

2023-02-09 08:13 UTC, agnesLeroy commented on concrete-cuda/cuda/src/crypto/gadget.cuh
> +    for (int j = 0; j < num_poly; j++) {
Ok agreed, a comment should be enough for us to keep track of what we can do with the function.

2023-02-09 08:14 UTC, agnesLeroy commented on concrete-cuda/cuda/src/polynomial/functions.cuh
> +    // accumulator.reverse_inplace();
I was confused about line 219 which is pseudo code, but we don't actually have a reverse_inplace() function in the code base. Maybe replacing the pseudo code with an explanation would be clearer?

2023-02-09 13:02 UTC, pdroalves commented on concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_3.rs
> +                    - <Precision::Raw as CastInto<i64>>::cast_into(obtained))
Fixture3 tests the PBS for different parameters, with k>1. I couldn't find a way to check which engine was being tested, so I couldn't avoid using those new parameters on the low latency kernel, which does not support k>1 yet.

2023-02-09 13:09 UTC, agnesLeroy commented on concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_3.rs
> +                    - <Precision::Raw as CastInto<i64>>::cast_into(obtained))
Oh ok makes sense. It's a shame to add a new fixture then but we can remove it when low lat PBS supports k > 1 as well. No problem for me :slightly_smiling_face:

2023-02-09 13:24 UTC, pdroalves commented
I added a comment explaining how the `GadgetMatrix` works. Moreover, I also changed all the functions in `functions.cuh` to receive a number of concatenate polynomials instead of `glwe_dimension`, except for the `sample_*` methods since it makes sense to talk about GLWEs in that context.

2023-02-09 13:24 UTC, pdroalves commented
@slab-ci gpu_test

2023-02-09 13:26 UTC, pdroalves commented on concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_3.rs
> +                    - <Precision::Raw as CastInto<i64>>::cast_into(obtained))
Totally! It is just temporary.

2023-02-09 16:14 UTC, merged