refactor(cuda): start scratch for amortized PBS
zama-ai/concrete-core pull request #333
Opened 2023-02-16 10:03 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-02-16 10:03 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-16 13:08 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-16 14:33 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-16 18:50 UTC, pdroalves requested changes
Everything looks good. I think we only need to add support to N=256 on the amortized PBS scratch function.

2023-02-16 18:50 UTC, pdroalves commented on concrete-cuda/cuda/src/bootstrap_amortized.cu
> +  case 512:
We already support `256`. We need a new clause in this `switch`.

2023-02-16 18:50 UTC, pdroalves commented on concrete-cuda/cuda/src/bootstrap_amortized.cu
> +  case 512:
Here too.

2023-02-16 18:50 UTC, pdroalves commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +get_full_sm_bootstrap_amortized(uint32_t polynomial_size,
May we rename this function to `get_buffer_size_full_sm_bootstrap_amortized`?

2023-02-16 18:50 UTC, pdroalves commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +get_partial_sm_bootstrap_amortized(uint32_t polynomial_size,
May we rename this function to `get_buffer_size_partial_sm_bootstrap_amortized`?

2023-02-17 08:05 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +get_full_sm_bootstrap_amortized(uint32_t polynomial_size,
Sure!

2023-02-17 08:06 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bootstrap_amortized.cuh
> +get_partial_sm_bootstrap_amortized(uint32_t polynomial_size,
Np

2023-02-17 08:07 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-17 11:57 UTC, pdroalves approved these changes

2023-02-17 12:51 UTC, merged