Refactor/cuda/low lat pbs scratch
zama-ai/concrete-core pull request #334
Opened 2023-02-16 16:24 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-02-16 16:24 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-16 16:51 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-17 08:19 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-17 08:21 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-21 09:49 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-21 10:17 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-21 11:48 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-22 13:55 UTC, pdroalves requested changes
Nice job!
I just found some minor problem in two comments and left a question regarding some lwe array sizes.

2023-02-22 13:55 UTC, pdroalves commented on concrete-cuda/cuda/src/bit_extraction.cuh
> +         + (polynomial_size + 1) * sizeof(Torus)  // lwe_array_in_buffer
Are you sure the size of the input LWE is `polynomial_size + 1` and not `glwe_dimension * polynomial_size +1`?

2023-02-22 13:55 UTC, pdroalves commented on concrete-cuda/src/cuda_bind.rs
> +    /// the amortized PBS on 64 bits inputs, into `pbs_buffer`. It also configures SM
amortized => low_latency

2023-02-22 13:55 UTC, pdroalves commented on concrete-cuda/src/cuda_bind.rs
> +    /// the amortized PBS on 32 bits inputs, into `pbs_buffer`. It also configures SM
amortized => low_latency

2023-02-22 14:20 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bit_extraction.cuh
> +         + (polynomial_size + 1) * sizeof(Torus)  // lwe_array_in_buffer
I have no idea... :disappointed:

2023-02-22 14:25 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bit_extraction.cuh
> +         + (polynomial_size + 1) * sizeof(Torus)  // lwe_array_in_buffer
It should be glwe_dimension * polynomial_size + 1 indeed.

2023-02-22 14:25 UTC, agnesLeroy commented on concrete-cuda/cuda/src/bit_extraction.cuh
> +         + (polynomial_size + 1) * sizeof(Torus)  // lwe_array_in_buffer
I'll fix it

2023-02-22 14:28 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-02-22 15:45 UTC, pdroalves approved these changes

2023-02-22 15:49 UTC, merged