chore(cuda): assert r value is positive in wop pbs
zama-ai/concrete-core pull request #343
Opened 2023-03-09 16:39 UTC by agnesLeroy

### Resolves: `<link_your_issue_here>`

### Description

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2023-03-09 16:40 UTC, agnesLeroy commented
@slab-ci gpu_test

2023-03-13 20:25 UTC, pdroalves approved these changes
Looks good. I think this code would become more readable and easier to maintain if we encapsulate these asserts in a function that receives the number of inputs and the polynomial size and returns a boolean, but it works for me as it is. Your call :-)

2023-03-13 20:27 UTC, pdroalves requested changes

2023-03-14 09:45 UTC, agnesLeroy commented
> Looks good. I think this code would become more readable and easier to maintain if we encapsulate these asserts in a function that receives the number of inputs and the polynomial size and returns a boolean, but it works for me as it is. Your call :-)

Thanks, I'll transfer this PR to concrete-open-source as soon as we have the tests there.

2024-05-14 13:44 UTC, closed without merging