doc(core): write user documentation for the new backends
zama-ai/concrete-core pull request #74
Opened 2022-06-27 09:12 UTC by agnesLeroy

### Resolves: zama-ai/concrete-core-internal#93
### Description
Write user documentation for default, fftw and cuda backends (with tutorials)

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-06-27 15:06 UTC, agnesLeroy commented
@aquint-zama @aPere3 @IceTDrinker we can release as soon as this one is merged basically :slightly_smiling_face:

2022-06-27 17:13 UTC, aquint-zama requested changes

2022-06-27 17:13 UTC, aquint-zama commented on concrete-core/docs/api/backend_cuda.md
> +There are two engine structures in the Cuda backend: the `CudaEngine` and the `AmortizedCudaEngine`.
I would set a `Title2: Engines` with 2 Title3 `CudaEngine` and `AmortizedCudaEngine` otherwise this sentence is a bit weird here.

2022-06-27 17:13 UTC, aquint-zama commented on concrete-core/docs/api/backend_cuda.md
> +And to copy from the GPU to the CPU:
missing a line break `And to copy` ends up after `Keyswitch keys`

2022-06-27 17:13 UTC, aquint-zama commented
I need to adapt it to Gitbook too but let first validate the content

2022-06-28 14:35 UTC, IceTDrinker reviewed
Hey @agnesLeroy thank you very much for the docs PR, some small comments

and a question in order to make keeping this documentation valid less complicated through a dedicated github repo potentially

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_cuda.md
> +         let l = (i as f64 * 2_f64.powi((64 - log_degree - 1) as i32)) as u64;
undefined log_degree, I'm guessing it's the 60 just above ?

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_cuda.md
> +     let mut fftw_engine = FftwEngine::new(()).unwrap();
do we really need the fftw_engine in the cuda tutorial it seems the convert from CUDA does everything (CPU to GPU + Standard to Fourier domain)

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/general_concepts.md
> +. This means that it represents binary LWE secret keys.
I think there was a mistake here core -> default

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +It is totally LLVM compatible, which makes it lightweight and very portable.
what does "totally LLVM compatible" mean here ?

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +concrete-core = {version = "=1.0.0-gamma", features=["backend_default", "parallel"]}
feature parallel was renamed, for the default backend it is `backend_default_parallel`

Maybe we should have an example github repo we can link people to, to avoid having these hard to review files in here and keep the example repo up to date more easily, don't know if it makes sense

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +```
shell or console not asm

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +The full list of engines and entities implemented in the default backend is available in the [Rust documentation](FIXME).
FIXME ?

2022-06-28 14:35 UTC, IceTDrinker commented on concrete-core/docs/api/backend_fftw.md
> +    engine.trivially_encrypt_glwe_ciphertext(glwe_dim.to_glwe_size(),
this does not manage the last half mega case sign to have the negacyclic property on the LUT, is it OK ?

2022-06-30 11:31 UTC, agnesLeroy commented on concrete-core/docs/api/backend_cuda.md
> +The benchmarking results shown above only relate to one set of cryptographic parameters, but bear in mind that performance varies depending on the parameters’ choice. In order to ease the user’s life
Not yet no, let me change this sentence.

2022-06-30 11:43 UTC, agnesLeroy commented on concrete-core/docs/api/backend_default.md
> +It is totally LLVM compatible, which makes it lightweight and very portable.
If think I should write instead that  there is nothing hardware specific in it.

2022-06-30 11:45 UTC, agnesLeroy commented on concrete-core/docs/api/backend_default.md
> +concrete-core = {version = "=1.0.0-gamma", features=["backend_default", "parallel"]}
Yes definitely the way i did things here is unmantainable :disappointed:

2022-06-30 11:53 UTC, agnesLeroy commented on concrete-core/docs/api/backend_fftw.md
> +    engine.trivially_encrypt_glwe_ciphertext(glwe_dim.to_glwe_size(),
Actually I don't know how I should create this LUT. Also I'm not rounding the decrypted result. We should definitely improve this tutorial...

2022-06-30 11:54 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +concrete-core = {version = "=1.0.0-gamma", features=["backend_default", "parallel"]}
don't worry Agnès, we can't get everything right the first time and generally code doc is broken online even on big projects, we'll try to come up with something when we have time :)

2022-06-30 12:02 UTC, IceTDrinker commented on concrete-core/docs/api/backend_default.md
> +concrete-core = {version = "=1.0.0-gamma", features=["backend_default", "parallel"]}
yes ! though the Cargo.toml thing might be a bit tricky

2022-06-30 12:33 UTC, agnesLeroy commented on concrete-core/docs/api/backend_default.md
> +concrete-core = {version = "=1.0.0-gamma", features=["backend_default", "parallel"]}
Oh yes indeed

2022-07-06 09:19 UTC, aquint-zama commented
> The concrete-core README.md being used as the gitbook doc homepage is a double edged sword I think, end users may be missing a Cargo.toml file potentially and we don't link to the concrete-core repo :/
> 
> Which is perfectly fine for github, I'm not so sure for gitbook

We could have one for Gitbook, it was just to fill the blank but feel free to add a README.md in docs and update the SUMMARY accordingly

2022-07-06 09:47 UTC, agnesLeroy commented
> > The concrete-core README.md being used as the gitbook doc homepage is a double edged sword I think, end users may be missing a Cargo.toml file potentially and we don't link to the concrete-core repo :/
> > Which is perfectly fine for github, I'm not so sure for gitbook
> 
> We could have one for Gitbook, it was just to fill the blank but feel free to add a README.md in docs and update the SUMMARY accordingly

I think for now it's ok to leave it like this. This way we don't have to update the example in 2 different places.

2022-07-06 09:48 UTC, IceTDrinker commented
> > > The concrete-core README.md being used as the gitbook doc homepage is a double edged sword I think, end users may be missing a Cargo.toml file potentially and we don't link to the concrete-core repo :/
> > > Which is perfectly fine for github, I'm not so sure for gitbook
> > 
> > 
> > We could have one for Gitbook, it was just to fill the blank but feel free to add a README.md in docs and update the SUMMARY accordingly
> 
> I think for now it's ok to leave it like this. This way we don't have to update the example in 2 different places. What do you think @IceTDrinker?

I agree, it's just something worth keeping in mind 🙂

2022-07-06 09:52 UTC, aPere3 approved these changes
Thanks a lot for this effort @agnesLeroy :muscle: , it's great !

Only two minor comments :wink:

2022-07-06 09:52 UTC, aPere3 commented on concrete-core/docs/backends/backend_default.md
> +```asm
toml instead of asm here !

2022-07-06 09:52 UTC, aPere3 commented on concrete-core/docs/getting_started/general_concepts.md
> +In the `engines` module, we find three modules, each dedicated to a type:
The module hierarchy is not visible to the user actually. What he sees is three engines at the level of `engines`.

2022-07-06 10:52 UTC, merged