Feature/bit extraction
zama-ai/concrete-core pull request #99
Opened 2022-07-18 16:09 UTC by IceTDrinker

### Resolves:

closes https://github.com/zama-ai/concrete-core-internal/issues/313

### Description

This PR is only the private API part to integrate the work done in concrete.

This is done to make crypto reviews easier by avoiding additional noise from the public API and fixtures e.g.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
~~* [ ] The draft release description has been updated~~
* [x] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2022-07-18 16:10 UTC, IceTDrinker commented
@slab-ci cpu_test

2022-07-20 07:00 UTC, aPere3 reviewed
Hello @IceTDrinker ,

Thanks for this PR !

I think I would definitely need an explanation on how the Wop-Pbs operator works, because it is pretty difficult for me to say whether the implementation is right :sweat_smile: 

I have a few minor comments / questions but nothing blocking !

2022-07-20 07:29 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    number_of_bits_to_extract: usize,
sounds good, I'll do something for that

2022-07-20 07:31 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        let mut output_ct = output_lwe_list.ciphertext_iter_mut().next().unwrap();
Probably, where should I call first, on the iterator itself ?

2022-07-20 07:32 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        let mut output_ct = output_lwe_list.ciphertext_iter_mut().next().unwrap();
I don't think the LweList has that

2022-07-20 07:33 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        ksk.keyswitch_ciphertext(&mut output_ct, &lwe_in_buffer);
Yes exactly, I got confused while getting the code from core experimental and mixed two versions of the code at first, now this is the right one and LWE ciphertexts all are under the same key

2022-07-20 07:34 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +            let decrypted_extract_bit = ((decrypted_with_carry >> 1) + carry) % 2;
this is the rounding phase when decrypting an LWE ciphertext

We first shift by 62 keeping the two highest bits

Then we get the carry bit, the last line is the rounding operation itself

2022-07-20 07:34 UTC, aPere3 commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        let mut output_ct = output_lwe_list.ciphertext_iter_mut().next().unwrap();
You would use `output_lwe_list.ciphertext_iter_mut().first().unwrap()` I think !

2022-07-20 07:35 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    );
yep, my guess is LLVM was already optimizing and getting them out of the loop if it can prove you don't need to reallocate

2022-07-20 07:40 UTC, aPere3 commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        ksk.keyswitch_ciphertext(&mut output_ct, &lwe_in_buffer);
Okay, good to know :wink:

2022-07-20 07:48 UTC, aPere3 commented
> This part is the bit extraction and should be pretty straight forward, I think I added the docstring explaining what it does

I don't think I would use the word `straightforward` for anything related to crypto :sweat_smile: hahaha. 

Let's discuss that in person then :wink:

2022-07-20 07:50 UTC, IceTDrinker commented
> > This part is the bit extraction and should be pretty straight forward, I think I added the docstring explaining what it does
> 
> I don't think I would use the word `straightforward` for anything related to crypto 😅 hahaha.
> 
> Let's discuss that in person then 😉

Yes sorry straightforward is not the right term my bad x)

2022-07-20 08:29 UTC, IceTDrinker commented
Done for the extracted bits thing, I ended up putting it in commons directly

2022-07-20 08:29 UTC, IceTDrinker commented
@slab-ci cpu_test

2022-07-20 11:57 UTC, damienligier requested changes
there are a few things to change :-)

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +/// the highest bit of the corresponding output message.
hightest -> most significant bit of the plaintext, i.e. scaled by q/2

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +/// number `delta_log` (0-indexed) included.
what is "indexed"? isn't it (0, ...,number_of_bits_to_extract-1)?

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    // If we only want to extract 1 bit then the last bit we extract is the one at delta_log so
this comment is confusing, it should be simpler like "compute the scaling factor for the last bit to extract"

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    let need_to_extract_highest_bit = last_bit_to_extract_index == ciphertext_n_bits - 1;
I don't understand why we do that. whether or not the last bit to extract is is the MSB, we never need to compute the last extraction.

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    // We iterate on the list in reverse as we want to store the MSB at index 0
MSB -> extracted MSB

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        // Add q/4 to manage negacyclicity for the PBS with unknwon padding bit
the comment is not correct. "add q/4 to center the error while computing a negacyclic LUT"

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        // Fill lut for the current bit (equivalent to trivial encryption as mask is 0s)
also add "The LUT is filled with -alpha in each coefficient where alpha = delta*2^{bit_idx-1}"

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        // PBS
add "applying a negacyclic LUT on a ciphertext with one bit of message in the MSB and no bit of padding"

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        // Add delta_log - 1 to manage negacyclicity for the PBS with unknown padding bit
delta_log - 1 -> alpha where alpha =  delta*2^{bit_idx-1}

the comment is not correct: "to end up with an encryption of 0 if the extracted bit was 0 and 1 in the other case"

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    if need_to_extract_highest_bit {
to remove

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +    for val in 0..1 << 5 {
why do we loop over 32 possible messages? it should be a randomized test whith a parameter for the number of iterations

2022-07-20 11:57 UTC, damienligier commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +            let decrypted_extract_bit = ((decrypted_with_carry >> 1) + carry) % 2;
why do we re-implement a rounding here? we should use the rounding already implemented instead

2022-07-20 13:04 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    let need_to_extract_highest_bit = last_bit_to_extract_index == ciphertext_n_bits - 1;
The naming is probably wrong on my end, I wanted to make the management of the special case of the MSB extraction explicit

2022-07-20 13:33 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +            let decrypted_extract_bit = ((decrypted_with_carry >> 1) + carry) % 2;
As discussed this should use a decomposer with a single block to re-use the rounding logic, will update that in the next patch

2022-07-20 13:33 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +    for val in 0..1 << 5 {
as discussed make 5 a variable up in the code

loop a certain number of times (e.g. 32 times like here as overall testing time was about 2-3 seconds on my development laptop) but generate random plaintexts

2022-07-20 13:35 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    if need_to_extract_highest_bit {
As discussed there needs to be a special handling of the last bit being extracted regardless of it being the highest bit or just the last bit to extract.

I'll rework the code and check whether this block of code is required or if it can be managed in the loop above a bit differently

2022-07-20 13:51 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/mod.rs
> +pub mod wop_pbs;
Issue for naming : https://github.com/zama-ai/concrete-core-internal/issues/330

2022-07-20 14:39 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +            let decrypted_extract_bit = ((decrypted_with_carry >> 1) + carry) % 2;
done

2022-07-20 14:40 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +    if need_to_extract_highest_bit {
Was removed in the rework, we now check in the loop if we should stop after the keyswitch if we processed the last bit that needed to be extracted

2022-07-20 14:46 UTC, IceTDrinker commented
@slab-ci cpu_test

2022-07-21 13:57 UTC, jborfila commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +/// Bits are outputed in one message each and are orderd from MSB to LSB. The extracted bit is in
Ouput bits are ordered from the MSB to the LSB. Each one of them is output in a distinct LWE ciphertext,
containing the encryption of the bit scaled by q/2 (i.e., the most significant bit in the plaintext representation).

2022-07-21 14:15 UTC, jborfila commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
> +        // Sub the result to the first LWE to have a 0 instead of the bit we just extracted
Comment change:
Remove the extracted bit from the initial LWE to get a 0 at the extracted bit location.

2022-07-21 14:17 UTC, jborfila commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +    //Define setting
Comment change (if needed?):
Define settings for an insecure toy example

2022-07-21 14:26 UTC, jborfila reviewed
Nice! Only small changes on comments requested.

2022-07-21 14:49 UTC, IceTDrinker commented on concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
> +    //Define setting
All done, thanks!

2022-07-22 13:22 UTC, IceTDrinker commented
@damienligier and @jborfila if you can check the last patch is good for merging 🙂 

thanks !

2022-08-08 09:35 UTC, damienligier approved these changes

2022-08-11 17:15 UTC, jborfila approved these changes

2022-08-12 07:48 UTC, merged